//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeahTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YeahTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings.Internal Trace 的本地化字符串。
        /// </summary>
        internal static string AdvancedSettingsInternalTrace {
            get {
                return ResourceManager.GetString("AdvancedSettingsInternalTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeBuilder Exit 的本地化字符串。
        /// </summary>
        internal static string CodeBuilderExit {
            get {
                return ResourceManager.GetString("CodeBuilderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Generation.General 的本地化字符串。
        /// </summary>
        internal static string CodeGenerationGeneral {
            get {
                return ResourceManager.GetString("CodeGenerationGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigurationSection {0} load failure 的本地化字符串。
        /// </summary>
        internal static string ConfigurationSectionLoadFailure {
            get {
                return ResourceManager.GetString("ConfigurationSectionLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSource Manager.DataSources 的本地化字符串。
        /// </summary>
        internal static string DataSourceManagerDataSources {
            get {
                return ResourceManager.GetString("DataSourceManagerDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayName or FileName cann&apos;t set empty 的本地化字符串。
        /// </summary>
        internal static string DisplayNameOrFileNameCanntSetEmpty {
            get {
                return ResourceManager.GetString("DisplayNameOrFileNameCanntSetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit template file failure! 的本地化字符串。
        /// </summary>
        internal static string EditTemplateFileFailure {
            get {
                return ResourceManager.GetString("EditTemplateFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment.Recent Files 的本地化字符串。
        /// </summary>
        internal static string EnvironmentRecentFiles {
            get {
                return ResourceManager.GetString("EnvironmentRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export DataSource Failure 的本地化字符串。
        /// </summary>
        internal static string ExportDataSourceFailure {
            get {
                return ResourceManager.GetString("ExportDataSourceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export DataSource {0} 的本地化字符串。
        /// </summary>
        internal static string ExportDataSourceFormat {
            get {
                return ResourceManager.GetString("ExportDataSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export {0} 的本地化字符串。
        /// </summary>
        internal static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export PDM File Failure 的本地化字符串。
        /// </summary>
        internal static string ExportPDMFileFailure {
            get {
                return ResourceManager.GetString("ExportPDMFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Failure 的本地化字符串。
        /// </summary>
        internal static string GenerateFailure {
            get {
                return ResourceManager.GetString("GenerateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generation Settings (*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string GenerationSettingsFileExt {
            get {
                return ResourceManager.GetString("GenerationSettingsFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Generation Settings File 的本地化字符串。
        /// </summary>
        internal static string InvalidGenerationSettingsFile {
            get {
                return ResourceManager.GetString("InvalidGenerationSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load configuration failure 的本地化字符串。
        /// </summary>
        internal static string LoadConfigurationFailure {
            get {
                return ResourceManager.GetString("LoadConfigurationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified 的本地化字符串。
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name or Connectionstring cann&apos;t set empty 的本地化字符串。
        /// </summary>
        internal static string NameOrConnectionstringCanntSetEmpty {
            get {
                return ResourceManager.GetString("NameOrConnectionstringCanntSetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Found {0} {1} Data Type Item 的本地化字符串。
        /// </summary>
        internal static string NotFoundDataTypeItem {
            get {
                return ResourceManager.GetString("NotFoundDataTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Found {0} To {1} Data Type Mapping 的本地化字符串。
        /// </summary>
        internal static string NotFoundDataTypeMapping {
            get {
                return ResourceManager.GetString("NotFoundDataTypeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The powerdesigner physical data model(pdm) not specify DBMS. 的本地化字符串。
        /// </summary>
        internal static string NotFoundPdmDBMSExceptionMessage {
            get {
                return ResourceManager.GetString("NotFoundPdmDBMSExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry!CodeBuilder not support this database. 的本地化字符串。
        /// </summary>
        internal static string NotSupportDatabaseExceptionMessage {
            get {
                return ResourceManager.GetString("NotSupportDatabaseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Code Generation Folder 的本地化字符串。
        /// </summary>
        internal static string OpenCodeGenerationFolder {
            get {
                return ResourceManager.GetString("OpenCodeGenerationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Code Generation Folder Failure! 的本地化字符串。
        /// </summary>
        internal static string OpenCodeGenerationFolderFailure {
            get {
                return ResourceManager.GetString("OpenCodeGenerationFolderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open {0} 的本地化字符串。
        /// </summary>
        internal static string OpenFormat {
            get {
                return ResourceManager.GetString("OpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Generation Settings File 的本地化字符串。
        /// </summary>
        internal static string OpenGenerationSettingsFile {
            get {
                return ResourceManager.GetString("OpenGenerationSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open PowerDesigner PDM File 的本地化字符串。
        /// </summary>
        internal static string OpenPowerDesignerPDMFile {
            get {
                return ResourceManager.GetString("OpenPowerDesignerPDMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package name is invalid,please input the english letters. 的本地化字符串。
        /// </summary>
        internal static string PackageNameInvalid {
            get {
                return ResourceManager.GetString("PackageNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physical Data Model (*.pdm)|*.pdm 的本地化字符串。
        /// </summary>
        internal static string PhysicalDataModelFileExt {
            get {
                return ResourceManager.GetString("PhysicalDataModelFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove datasource item failure! 的本地化字符串。
        /// </summary>
        internal static string RemoveDatasourceItemFailure {
            get {
                return ResourceManager.GetString("RemoveDatasourceItemFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove template item failure! 的本地化字符串。
        /// </summary>
        internal static string RemoveTemplateItemFailure {
            get {
                return ResourceManager.GetString("RemoveTemplateItemFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save configuration failure 的本地化字符串。
        /// </summary>
        internal static string SaveConfigurationFailure {
            get {
                return ResourceManager.GetString("SaveConfigurationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved 的本地化字符串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save DataSource Items Failure 的本地化字符串。
        /// </summary>
        internal static string SaveDataSourceItemsFailure {
            get {
                return ResourceManager.GetString("SaveDataSourceItemsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Environment.RecentFiles Failure! 的本地化字符串。
        /// </summary>
        internal static string SaveEnvironmentRecentFilesFailure {
            get {
                return ResourceManager.GetString("SaveEnvironmentRecentFilesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save {0}... 的本地化字符串。
        /// </summary>
        internal static string SaveFormat {
            get {
                return ResourceManager.GetString("SaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Generation Settings File 的本地化字符串。
        /// </summary>
        internal static string SaveGenerationSettingsFile {
            get {
                return ResourceManager.GetString("SaveGenerationSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Options.CodeGeneration.General Failure 的本地化字符串。
        /// </summary>
        internal static string SaveOptionsCodeGenerationGeneralFailure {
            get {
                return ResourceManager.GetString("SaveOptionsCodeGenerationGeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Options.InternalTraceLevel Failure 的本地化字符串。
        /// </summary>
        internal static string SaveOptionsInternalTraceLevelFailure {
            get {
                return ResourceManager.GetString("SaveOptionsInternalTraceLevelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save/New template file failure! 的本地化字符串。
        /// </summary>
        internal static string SaveOrNewTemplateFileFailure {
            get {
                return ResourceManager.GetString("SaveOrNewTemplateFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save template file: {0} failure! 的本地化字符串。
        /// </summary>
        internal static string SaveTemplateFileFailure {
            get {
                return ResourceManager.GetString("SaveTemplateFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Template Items Failure! 的本地化字符串。
        /// </summary>
        internal static string SaveTemplateItemsFailure {
            get {
                return ResourceManager.GetString("SaveTemplateItemsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should checked a tables or views treenode 的本地化字符串。
        /// </summary>
        internal static string ShouldCheckedTreeNode {
            get {
                return ResourceManager.GetString("ShouldCheckedTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should select one template at least. 的本地化字符串。
        /// </summary>
        internal static string ShouldSelectOneTemplate {
            get {
                return ResourceManager.GetString("ShouldSelectOneTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting CodeBuilder 的本地化字符串。
        /// </summary>
        internal static string StartingCodeBuilder {
            get {
                return ResourceManager.GetString("StartingCodeBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup 的本地化字符串。
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tables 的本地化字符串。
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task ID parameter must be unique 的本地化字符串。
        /// </summary>
        internal static string TaskId {
            get {
                return ResourceManager.GetString("TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template file not found 的本地化字符串。
        /// </summary>
        internal static string TemplateFileNotFound {
            get {
                return ResourceManager.GetString("TemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Manager.Templates 的本地化字符串。
        /// </summary>
        internal static string TemplateManagerTemplates {
            get {
                return ResourceManager.GetString("TemplateManagerTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views 的本地化字符串。
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
